FROM golang:1.23.2-alpine3.20 AS builder

WORKDIR /usr/src/app

COPY . . 

RUN go build -ldflags '-s -w' fullcycle-rocks.go

FROM scratch

COPY --from=builder /usr/src/app/fullcycle-rocks .

CMD [ "./fullcycle-rocks" ]